name: Nightly TICS scan

on:
  schedule:
    - cron: '01 07 * * *' # Every day at 07:01 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  TICS:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.46.0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.9.25

      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic --channel latest/stable
      
      - name: Run coverage tests
        run: just unit
      
      - name: Activate tests .venv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: slurmutils
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ env.GITHUB_WORKSPACE }}
          ticsAuthToken: ${{ secrets.TICS_AUTH_TOKEN }}
          installTics: true
          calc: ALL
